<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Reviewer;
use App\Services\AchievementService;
use Illuminate\Support\Facades\DB;

class BackfillReviewerAchievements extends Command
{
    protected $signature = 'achievements:backfill-reviewers';
    protected $description = 'Retroactively count reviews and award badges for existing reviewers';

    public function handle()
    {
        $this->info('Starting backfill of reviewer achievements...');
        
        $reviewers = Reviewer::all();
        $achievementService = app(AchievementService::class);
        
        foreach ($reviewers as $reviewer) {
            $this->info("Processing reviewer: {$reviewer->username}");
            
            // Count approved questions (reviews where grade >= 70%)
            $approvedCount = DB::table('questions')
                ->where('reviewer_ID', $reviewer->reviewer_ID)
                ->where('status', 'Approved')
                ->count();
            
            // Count rejected questions (reviews where grade < 70%)
            $rejectedCount = DB::table('questions')
                ->where('reviewer_ID', $reviewer->reviewer_ID)
                ->where('status', 'Rejected')
                ->count();
            
            // Total reviews
            $totalReviews = $approvedCount + $rejectedCount;
            
            // Count questions generated by this reviewer (all questions with this reviewer_ID)
            $questionsGenerated = DB::table('questions')
                ->where('reviewer_ID', $reviewer->reviewer_ID)
                ->count();
            
            // Check if reviewer is qualified (passed competency test)
            $isQualified = DB::table('competency_test_results')
                ->where('reviewer_ID', $reviewer->reviewer_ID)
                ->where('passed', true)
                ->exists();
            
            // Update reviewer stats
            $reviewer->total_reviews = $totalReviews;
            $reviewer->clean_reviews_count = $approvedCount;
            $reviewer->errors_flagged_count = $rejectedCount;
            $reviewer->questions_generated_count = $questionsGenerated;
            $reviewer->isQualified = $isQualified ? 1 : 0;
            
            $reviewer->save();
            
            $this->info("  ✓ Total reviews: {$totalReviews}");
            $this->info("  ✓ Approved: {$approvedCount}");
            $this->info("  ✓ Rejected: {$rejectedCount}");
            $this->info("  ✓ Questions generated: {$questionsGenerated}");
            $this->info("  ✓ Is qualified: " . ($isQualified ? 'Yes' : 'No'));
            
            // Check and award badges
            $achievementService->checkReviewerBadges($reviewer);
            
            $badgeCount = $reviewer->badges()->count();
            $this->info("  🎖️  Badges earned: {$badgeCount}");
            $this->line('');
        }
        
        $this->info('✅ Backfill completed successfully!');
        return 0;
    }
}
